apiVersion: apps/v1
kind: Deployment
metadata:
  name: introbot2
  labels:
    app: introbot2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: introbot2
  template:
    metadata:
      labels:
        app: introbot2
    spec:
      containers:
        - name: introbot2
          image: samyousoftwire/introbot:latest
          envFrom:
            - secretRef:
                name: test-secret