apiVersion: apps/v1
kind: Deployment
metadata:
  name: introbot2
  labels:
    app: introbot2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: introbot2
  template:
    metadata:
      labels:
        app: introbot2
    spec:
      volumes:
        - name: introbot2-storage-storage
          persistentVolumeClaim:
            claimName: introbot2-storage-claim
      containers:
        - name: introbot2
          image: samyousoftwire/introbot:latest
          envFrom:
            - secretRef:
                name: test-secret
          volumeMounts:
            - mountPath: "/introbot"
              name: introbot2-storage-storage
