apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: introbot2-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi